### ISSUE TITLE
Goal time appears incorrect when playing live compaign

### ISSUE THREAD

**Issue by AmaSpirit** [Vanawy/tm-run-history#1]
![run history wrong time](https://user-images.githubusercontent.com/126785417/222438030-36c23aaf-eacf-4e8b-a8c6-71552e3708c0.png)

That's champion medal from previous map.

When playing solo problem doesn't exist

**Comment by Vanawy** [comment]
@AmaSpirit thank you for creating issue. I'll try to recreate and fix it!
