### ISSUE TITLE
Add setting to track no-respawn runs

### ISSUE THREAD

**Issue by TNTreee** [Vanawy/tm-run-history#10]
Many times while hunting you will reset most runs, or respawn to look at the no-respawn at the finish, which would just display as x seconds behind on Run History.
thus
Either by integrating with No-Respawn Timer or calculating it, no-respawn times should be able to be displayed on this plugin, perhaps in a different colour so that they aren't confused with regular times.

This would be especially helpful with #9 as you would be able to see what position a failed run would have been.

**Comment by Vanawy** [comment]
Implemented in 0.5.0 (not published yet)
