### ISSUE TITLE
Revisit default colors of delta time

### ISSUE THREAD

**Issue by Vanawy** [Vanawy/tm-run-history#16]
It's misleading rn (possibly brightness issue)

**Comment by FreezeHandz** [comment]
> Hi there. I always use your plugin and when I want to highlight certain deltas I can't see the difference between them because of their colours. So I found a workaround. I use less thresholds, but I use an extra one to have the next brighter colour. That way it is easier to see the differences. ![comparison](https://private-user-images.githubusercontent.com/93701993/311318058-07595e97-b49c-4e4d-a468-71b9cba4087f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjA5NTQsIm5iZiI6MTcwOTkyMDY1NCwicGF0aCI6Ii85MzcwMTk5My8zMTEzMTgwNTgtMDc1OTVlOTctYjQ5Yy00ZTRkLWE0NjgtNzFiOWNiYTQwODdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE3NTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNGRiYmU3YzVjZDE0YzhkZGY3ZTUzYjI1MzQzOTVjOTI0OWQ2OGJjOGY2MGE5OGY3YWFmNTMxNzViZGE0ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B29GJ63H4KLx7WWFv-H9rQInZEnwX_Gb1qXdbfEolVc)
> 
> Then I thought of a way to use the brightness factor so that each of the 8 possible deltas can be more different.
> 
> By using a gradient, I sat the start brightness at a low level (dark) and the end brightness at a high level (light). Then I picked the colour from the gradient using eight squares and taking their centre as a reference point
> 
> I made three paletes ![light color palete_](https://private-user-images.githubusercontent.com/93701993/311320820-c2bd8d67-a642-4ef2-b0f0-cbb8a286ec3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjA5NTQsIm5iZiI6MTcwOTkyMDY1NCwicGF0aCI6Ii85MzcwMTk5My8zMTEzMjA4MjAtYzJiZDhkNjctYTY0Mi00ZWYyLWIwZjAtY2JiOGEyODZlYzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE3NTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwM2IxNWFjZDEzZjUxYWY2OWJiNDYxYzdmNmM0NzIwYTVhNGU1N2ZjZDA5OGYzYzljMWFkMjU0YWFlOTM3NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06feoU2vyB4KIGuJMFBQARy0bahycNAfu9wM6i0Fk5U) ![dark color palete_](https://private-user-images.githubusercontent.com/93701993/311320855-d2929f8c-913f-4526-8854-da9a6e87ee40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjA5NTQsIm5iZiI6MTcwOTkyMDY1NCwicGF0aCI6Ii85MzcwMTk5My8zMTEzMjA4NTUtZDI5MjlmOGMtOTEzZi00NTI2LTg4NTQtZGE5YTZlODdlZTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE3NTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NjI3ZTg4NTk3NDJjN2JkN2Y1ZTgzNDVlYTcwYmM0MmZmMjc1N2RhMWUwZGMyZWQ1NGJiNGQ4YWY2Y2Q1NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.59Nchs75gvrAySFqn4M2AQ7mqNmOCojmbx-qgHhiIO0) ![three color palete_](https://private-user-images.githubusercontent.com/93701993/311320869-ef053cce-aadd-4299-a254-1728c31534e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjA5NTQsIm5iZiI6MTcwOTkyMDY1NCwicGF0aCI6Ii85MzcwMTk5My8zMTEzMjA4NjktZWYwNTNjY2UtYWFkZC00Mjk5LWEyNTQtMTcyOGMzMTUzNGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE3NTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZTcwNGRkZjg2NGJkNGZmNjkxZmU1NmRjNTg0ZThmZGVjNDAwYTgxYzY0Nzc4YTg4ODMyOTYzZmE1YzJjODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a6AW_ysYJg5L07FxW8YYCWFeBIBC41r_0s9C0viFRN4)

So every start squares start with a shade of dark red and then ends with a light yellow

For the #0 delta, It could be a purple. Or it can be hidden. Because most of the time I don't care what the delta is beyond the last one that I set.

If you need the exact HEX of the square I can share them xD

**Comment by Vanawy** [comment]
I tried 1st and 3rd pallets. Brightest looks a lot better imo, dark one is blending with dark background too much.

**Comment by Vanawy** [comment]
New color palette implemented in 0.4.3
