### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by FreezeHandz** [Vanawy/tm-run-history#29]
Since the last update, the plugin doesn't save finished runs

**Comment by Vanawy** [comment]
> Since the last update, the plugin doesn't save finished runs

Hello, can you confirm that "PBs only" is not checked in plugin settings?
It's new setting I added so it's might be the reason

**Comment by FreezeHandz** [comment]
I tried in all medals target and it doesn't save the runs. When I tried to set manually to "Default (closest target)", the plugin crushed. Here is a screenshot
![image](https://github.com/Vanawy/tm-run-history/assets/93701993/5e1266e3-cbd6-41a8-b73c-b9b633b233b8)

**Comment by FreezeHandz** [comment]
> an you confirm that "PBs only" is not checked in plugin s

I checked the plugin settings and it's off

**Comment by Vanawy** [comment]
@FreezeHandz thank you for screenshot. My bad. I'll fix it asap. 

I guess you can try to install Champion Medals plugin for now and check if it'll work

**Comment by FreezeHandz** [comment]
After I installed Champion Medals, it works fine. I didn't use that plugin before. I guess I will hide it xD. Thank you for helping

**Comment by Vanawy** [comment]
> After I installed Champion Medals, it works fine. I didn't use that plugin before. I guess I will hide it xD. Thank you for helping

I use it it hidden all the time ;) Thank you again for reporting this issue.

**Comment by Vanawy** [comment]
Fixed in 0.4.2
