### ISSUE TITLE
Suggested new features

### ISSUE THREAD

**Issue by FreezeHandz** [Vanawy/tm-run-history#4]
Hello, I've been using your Trackmania2020 plugin 'Run history" for a while and I was wondering if you could add these features:

- Changing time reference to any medals, PB, or WR time of the current map
- Changing the threshold of how the color of delta time changes
- Shortcut or button for deleting all run history

**Comment by Vanawy** [comment]
@FreezeHandz I added ability to change reference time and clear records list. Working on delta thresholds rn.

I'm not sure about WR time target. Created separate issue for it - you can subscribe if you wish - #7 .

I'll sent new plugin version for review today (with or without threshold change function). 

![image](https://github.com/Vanawy/tm-run-history/assets/18261094/a3337999-8578-4df5-9df8-e2098fe5210b)

**Comment by FreezeHandz** [comment]
I like the overlay, nice! I can't wait to see the final version. 
I don't mind if WR time target doesn't work. Having just medal and PB times is fine.

**Comment by Vanawy** [comment]
New version is on review and will bi published as soon as it is signed 
![image](https://github.com/Vanawy/tm-run-history/assets/18261094/bacf8de6-8929-4750-8c17-c6d15c31643a)
